// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1l0yixyoqUvTyXSda3uJ-hhIO9N1g8rU',
    appId: '1:778397785626:web:ebf63e6839585cae73fba3',
    messagingSenderId: '778397785626',
    projectId: 'netflix-clone-test-87afb',
    authDomain: 'netflix-clone-test-87afb.firebaseapp.com',
    storageBucket: 'netflix-clone-test-87afb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Y2FduZHm9LUtEnTXLDbOGbU2m0fgZDo',
    appId: '1:778397785626:android:401016be85419f9273fba3',
    messagingSenderId: '778397785626',
    projectId: 'netflix-clone-test-87afb',
    storageBucket: 'netflix-clone-test-87afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyhbvuniAcfU_cMl31QHfVsMElC0xd9wk',
    appId: '1:778397785626:ios:717c1d65e746bec073fba3',
    messagingSenderId: '778397785626',
    projectId: 'netflix-clone-test-87afb',
    storageBucket: 'netflix-clone-test-87afb.appspot.com',
    iosBundleId: 'com.example.netflixCloneTest',
  );
}
